### ISSUE TITLE
data element: Date of Birth or Age

### ISSUE THREAD

**Issue by davidhuser** [SwissTPH/dhis2_va_draft#15]
Date of Birth
**or**
Age (in Years?)

**Comment by mbratschi** [comment]
DoB should be 1st option with the possibility of entering age if DoB is unknown. Need to see how this is structured in the questionnaire as that is where the data will come from

**Comment by gocastro** [comment]
it is either one or the other - does this make sense?

**Comment by davidhuser** [comment]
This would lead to the creation of a Program Rule as the DHIS2 program can not detect if one or another was filled out without a rule.

**Comment by mbratschi** [comment]
yes should be either one or the other. should structure like in the MCCOD module. need to see with Sam and Erin how data comes from the questionnaire if Date of Birth is unknown

**Comment by davidhuser** [comment]
Resulting issue created - https://github.com/SwissTPH/openVA-dhis2/issues/26

**Comment by davidhuser** [comment]
Needs to be enforced from the Pusher (i.e. openVA). (?)

**Comment by davidhuser** [comment]
A note that DHIS2 supports the data element value type "AGE" in 2.26 onwards -  this however stores the actual age dynamically, e.g. it updates every day:
https://docs.dhis2.org/2.26/en/user/html/dhis2_user_manual_en_full.html#d1247e5639
