### ISSUE TITLE
data element: metadata on how COD was obtained

### ISSUE THREAD

**Issue by davidhuser** [SwissTPH/dhis2_va_draft#18]
What should be exactly in this metadata?

**Comment by gocastro** [comment]
I believe this would be the content of the BLOB, to be confirmed.

**Comment by gocastro** [comment]
this is actually 2 fields:
- 1 field for code associated with combination of - algorithm, type of training data, version of the algorithm 
- 1 field for SQLlite (BLOB)

**Comment by gocastro** [comment]
what was the SQLLite field for?

**Comment by davidhuser** [comment]
Storing the ID for the fileResource

**Comment by gocastro** [comment]
Sam still to provide the full list for the field with algorithm, type of training data, version of the algorithm

**Comment by gocastro** [comment]
each option will include:

- ID
- Name

(which refer to metadata stored in the BLOB that includes:
- ID
- Name
- Algorithm_id
- Algorithm_name
- Algorithm_version
- Sci_id
- Sci_name
- Sci_version
- Instrument_id
- Instrument_name
- Instrument_version
)

list of options is still to be provided

**Comment by davidhuser** [comment]
Suggested formulas for options of option set: (`<...>` are markers for variables)

**Code** (delimited by a | because versions include an underscore already):
```
<Algorithm name>|<Algorithm Version>|<SCI Name>|<SCI Version>|<Instrument Name>|<Instrument Version>
```


**Name:**
```
<Algorithm name> (<Algorithm Version>) - <SCI Name> (<SCI Version>) - <Instrument Name> (<Instrument Version>)
```

pending for approval

**Comment by davidhuser** [comment]
approved
