### ISSUE TITLE
data element: option set for CoD

### ISSUE THREAD

**Issue by davidhuser** [SwissTPH/dhis2_va_draft#20]
Option Set with SMoL
with Options = ?

**Comment by gocastro** [comment]
I believe it should actually be ICD, to be confirmed

**Comment by mbratschi** [comment]
Sorry commented on the wrong issue. She should be ICD I think as well. Sam would have examples of this across algorithms when they did algorithm comparisons.....

**Comment by gocastro** [comment]
can we remove the question label?

**Comment by davidhuser** [comment]
If we have decided on which optionSet we're using then yes. Our possibilities

- create our own optionSet with codes like `E81.1`
- use the optionSet on play.dhis2.org/demo with codes like `E811`

**Comment by mbratschi** [comment]
Sam knows the outputs of the algorithms in general and in openVA the best and he should comment on this.

**Comment by davidhuser** [comment]
As per Sam's comment, we should use the full 7-character code *without* the fullstop `.`

**Comment by gocastro** [comment]
7-character? why 7? can you give an example

**Comment by gocastro** [comment]
confirmed in the WS that it will be the ICD code

**Comment by gocastro** [comment]
option set for CoD should be editable through API

**Comment by gocastro** [comment]
Sam still to provide full ICD list

**Comment by gocastro** [comment]
ICD list attached

[icd10_codes.txt](https://github.com/SwissTPH/dhis2_va_draft/files/1274629/icd10_codes.txt)
