### ISSUE TITLE
Program property: coordinates

### ISSUE THREAD

**Issue by davidhuser** [SwissTPH/dhis2_va_draft#23]
It's possible to submit coordinates along the event. Tablets support capturing coordinates.

**Comment by gocastro** [comment]
is this a requirement? it was not obvious to me so far... or do we mean that this is a potential future enhancement?

**Comment by mbratschi** [comment]
we are not routinely including coordinates and i don't think this is recommended. we should only include geographic information to the country-specified level of detail on the hierarchy of DHIS2 Organizational Units of that country (e.g. down to a District).

**Comment by gocastro** [comment]
got it, I am closing this issue.
