### ISSUE TITLE
Program rule: it needs either DoB or Age in Years

### ISSUE THREAD

**Issue by davidhuser** [SwissTPH/dhis2_va_draft#26]

**Comment by davidhuser** [comment]
confirmed - either or enforced by a program rule

**Comment by davidhuser** [comment]
program rule can't be enforced through the API, so it's both. Needs to be enforced from the openVA pipeline (to have one or the other).

**Comment by gocastro** [comment]
what is the question then?

**Comment by davidhuser** [comment]
This needs to make it into OpenVA, not the module.
