### ISSUE TITLE
Set up program

### ISSUE THREAD

**Issue by davidhuser** [SwissTPH/dhis2_va_draft#3]

**Comment by davidhuser** [comment]
What should be set for _Completed events expiry days_? I set it now to not lock it at any time.
> Defines the number of days for which you can edit a completed event. This means that when an event is completed and the specified number of expiry days has passed, the event is locked.

**Comment by gocastro** [comment]
Event being the creation of the VA output, right?

**Comment by davidhuser** [comment]
Hmm... Event = submitting the VA output into the program.

**Comment by davidhuser** [comment]
removing question, referencing this issue - https://github.com/SwissTPH/openVA-dhis2/issues/27
