### ISSUE TITLE
Aligning openVA causes of death with ICD10

### ISSUE THREAD

**Issue by jarathomas** [SwissTPH/dhis2_va_draft#31]
The causes of death assigned by openVA span several ICD10 categories (not always contiguous).  Is it possible to amend the "Most probable Cause of Death" option set so that it uses the mapping in the attached pdf?
[ICD10mapping.pdf](https://github.com/SwissTPH/dhis2_va_draft/files/1512854/ICD10mapping.pdf)

**Comment by gocastro** [comment]
we need combinations of a) ID and b) name

currently that is, e.g., 
a) B50 
b) Plasmodium falciparum malaria
your request would mean that this example will become 
a) B50-B54 
b) Malaria

is that it?

**Comment by jarathomas** [comment]
yes, and note that "Meningitis and encephalitis" is A39; G00-G05 (some of the "other" causes combine quite a few broad ICD10 categories)

**Comment by gocastro** [comment]
but should the 01.01 codes also be shown? 
@mbratschi can you please approve this change to the requirements? (please see discussion above)

**Comment by jarathomas** [comment]
I don't think the 01.01 codes are necessary, but it would be useful to have the names ("Sepsis (non-obstetric)", "Acute resp infect, incl pneumonia", etc.).  As long as there is a logical way to move from the WHO column (on the left) to the ICD10 column (on the right) -- here, I am referring to the pdf I posted in the initial message.  Please let me know if it would be useful to discuss.

**Comment by mbratschi** [comment]
@jarathomas can you please check with Don on the mapping of VA causes to ICD-10. if your PDF is the final mapping, the option set should be changed. i assume your PDF applies to InterVA5 and InSilico, right? if the cause list for Tariff 2.0 maps to different ICD-10 codes, i would suggest to include the "01.01" numbers after the name of the cause, e.g. "Sepsis (non-obstetric) (01.01)"

**Comment by jarathomas** [comment]
I don't think the 01.01 codes are necessary, but it would be useful to have the names ("Sepsis (non-obstetric)", "Acute resp infect, incl pneumonia", etc.).  As long as there is a logical way to move from the WHO column (on the left) to the ICD10 column (on the right) -- here, I am referring to the pdf I posted in the initial message.  Please let me know if it would be useful to discuss.

**Comment by jarathomas** [comment]
@mbratschi, I'll check with Don.  The PDF is very similar to InterVA5 -- only difference is that version 5 has one additional category (simply splitting a single category from version 4); and InSilico will use the same list as InterVA5.  SmartVA produces causes not always consistent with ICD10 (and Tariff can use any list, but training data with known causes must be provided).

**Comment by gocastro** [comment]
just keeping it open as we still do not have it implemented

**Comment by mbratschi** [comment]
Dear Jason,
Let’s see what Don says and then we can also discuss in Ghana.
Kind regards,
Martin



______________________________________________________________________________

Martin W. Bratschi
Deputy Director, Technical Implementation
Public Health Programs, CRVS Improvement
mbratschi@vitalstrategies.org<mailto:mbratschi@vitalstrategies.org>
M +65 9836 6421  |  Skype mbratschi

[cid:image002.png@01D32BE6.EDB8CCA0]

Vital Strategies
Building Public Health Systems Globally
-–
We envision a world where everyone is protected by a strong public health system.
Read stories from our work in our 2016 Annual Report at VitalStrategies.org/AnnualReport2016<https://www.vitalstrategies.org/annualreport2016>

**Comment by gocastro** [comment]
we will be using ICD-10+Tariff and WHO VA causes codes all together so that installations in different settings can accommodate different codes
