### ISSUE TITLE
Metadata and OU UID

### ISSUE THREAD

**Issue by ChipoHankumbaMuleya** [SwissTPH/dhis2_va_draft#42]
I made an initial installation using DHIS2 (2.29). I am across a problem when trying to import the metadata.I could import all the json files with no problem but the 'Verbal Autopsy' does not seem to appear under programs. So i figured it was a compatibility problem with version 2.29.

I therefore made a fresh install on a different VM using version 2.25. This presented me with a problem of the OU UID. Using the API query /api/organisationUnits?level=1 does not show me a UID, instead i get this;
`<metadata xmlns="http://dhis2.org/schema/dxf/2.0">
<pager>
<page>1</page>
<pageCount>1</pageCount>
<total>0</total>
<pageSize>50</pageSize>
</pager>
</metadata>`

What am i doing wrong?

**Comment by jarathomas** [comment]
Hello,

Just to make sure the basics are covered, did you [Link Program to Organisation Units](https://github.com/SwissTPH/dhis2_va_draft/blob/master/docs/Installation.md#link-program-to-organisation-units)?  Also, is the problem related to user privileges?

**Comment by davidhuser** [comment]
For the second issue: Looks like you don't have any Organisation Unit set up in your System.
See docs to set up one: https://docs.dhis2.org/2.25/en/user/html/dhis2_user_manual_en_full.html#d0e6894

If that's not true, try `/api/organisationUnits?filter=level:eq:1` instead ([demo](https://play.dhis2.org/2.25/api/organisationUnits?filter=level:eq:1)), or `/api/organisationUnits?filter=parent:null` ([demo](https://play.dhis2.org/2.25/api/organisationUnits?filter=parent:null)).

**Comment by ChipoHankumbaMuleya** [comment]
@jarathomas Thanks for your reply. Unfortunately, that is one of the issues i am having. Despite importing the va_program.json
metadata, the 'Verbal Autopsy' program does not show up as one of the programs. I am using the admin account so i doubt it is a privilage issue.

@davidhuser Thanks for your reply. Excuse my ignorance but this is a fresh install. My understanding (and experience from the 2.29 install) is that there should be a Level 1 OU UID, which in my case is none existent.  Do i then have to start creating OUs? I'm trying to follow the installation instructions.

**Comment by gocastro** [comment]
The VA program is only showing up as one of the programs when you assign it to organisational  units. It will then be visible for  those organisational units (in the Event Capture app). You can create organisational units using this example structure: https://github.com/SwissTPH/dhis2_va_draft/blob/master/demo_setup/metadata/example_organisationUnits_hierarchy.json

**Comment by davidhuser** [comment]
When you have a completely fresh install you usually do not have an organisation unit already present.

**Comment by ChipoHankumbaMuleya** [comment]
@davidhuser The same applies for the instructions but those very instructions instruct to get the Level 1 OU UID. It was available with the 2.2.9 install but not there with the 2.25. Both were fresh installs. The instructions i am referring to are at this link: https://github.com/SwissTPH/dhis2_va_draft/blob/master/docs/Installation.md, instruction number 5 under 'Preparation'.

This is all before the metadata files are imported.

**Comment by gocastro** [comment]
Indeed, with version 2.25 instruction number 5 can only be accomplished after you have created organisational units.

**Comment by ChipoHankumbaMuleya** [comment]
@gocastro Have you tried running the dhis2_va on 2.29?

**Comment by gocastro** [comment]
@ChipoHankumbaMuleya - no we did not try to run it on 2.29, the only supported version currently is 2.25. If there is the need for a version compatible with 2.29 (or other) we can work on it!

**Comment by ChipoHankumbaMuleya** [comment]
@gocastro Then i would suggest the installation instructions be edited to sort out the OU UID issue. They should state that OUs have to be created (possibly with instructions) prior to step 5.

**Comment by gocastro** [comment]
@ChipoHankumbaMuleya I now added that to the installation instructions that the organisational hierarchy needs to be in place in the server.  Please see here:  [dhis2_va_draft/docs/Installation.md](https://github.com/SwissTPH/dhis2_va_draft/blob/master/docs/Installation.md) (under "Import").
I will therefore close the issue.
